### ISSUE TITLE
Exception when unclicking Socket | Accept checkbox

### ISSUE THREAD

**Issue by rwbaer** [makehumancommunity/community-plugins#14]
Exception on Windows 10  (12-20-16 plugin version - I'm not sure how to track versioning for these plugins ??)

Steps to reproduce:
On socket tab, unclicking  Socket | Accept connections
----------------------------------------------------------------------------------------
```
Exception during event onClicked
Traceback (most recent call last):
  File "c:\jenkins\workspace\Windows_release_11x\buildscripts\win32\build\makehuman\out00-PYZ.pyz\events3d", line 211, in callEvent
  File "plugins/8_server_socket\__init__.py", line 52, in onClicked
    self.closeSocket()
  File "plugins/8_server_socket\__init__.py", line 119, in closeSocket
    self.socket.shutdown()
  File "c:\jenkins\workspace\Windows_release_11x\buildscripts\win32\build\makehuman\out00-PYZ.pyz\socket", line 224, in meth
TypeError: shutdown() takes exactly one argument (0 given)

```

On the other hand perhaps this is just user misunderstanding because I was not actually using the thing so there was no Blender server available.  

Clicking the socket check on and off produces this on the console:
```
Opening server socket... Bind failed. Error Code : 10048 Message Only one usage of each socket address (protocol/network address/port) is normally permitted
Closing socket.
Starting server thread.
Opening server socket... Bind failed. Error Code : 10048 Message Only one usage of each socket address (protocol/network address/port) is normally permitted
Closing socket.
Starting server thread.
Opening server socket... Bind failed. Error Code : 10048 Message Only one usage of each socket address (protocol/network address/port) is normally permitted
Closing socket.

```

**Comment by joepal1976** [comment]
This is fixed with patch from CKY
